import { DashboardData, DashboardPurchase, DashboardTicket, DashboardKPIs } from "./types";

export const MOCK_DASHBOARD_PURCHASES: DashboardPurchase[] = [
  {
    id: "pur-001",
    createdAt: "2026-11-10T14:23:00.000Z",
    buyerName: "María González",
    buyerEmail: "maria.gonzalez@example.com",
    buyerDni: "40123456",
    quantity: 3,
    totalAmount: 36000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812341",
    buyerParticipation: "asistir",
    referringVolunteer: "Campi",
  },
  {
    id: "pur-002",
    createdAt: "2026-11-10T16:45:00.000Z",
    buyerName: "Juan Manuel Navarro",
    buyerEmail: "juan.navarro@example.com",
    buyerDni: "38291234",
    quantity: 2,
    totalAmount: 24000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812342",
    buyerParticipation: "donacion",
    referringVolunteer: "Mili",
  },
  {
    id: "pur-003",
    createdAt: "2026-11-11T10:15:00.000Z",
    buyerName: "Agustina Rossi",
    buyerEmail: "agustina.rossi@austral.edu.ar",
    buyerDni: "42555666",
    quantity: 4,
    totalAmount: 48000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812343",
    buyerParticipation: "asistir",
    referringVolunteer: "Campi",
  },
  {
    id: "pur-004",
    createdAt: "2026-11-11T18:02:00.000Z",
    buyerName: "Lucas Benítez",
    buyerEmail: "lbenitez@empresa.com",
    buyerDni: "39112233",
    quantity: 1,
    totalAmount: 12000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812344",
    buyerParticipation: "asistir",
    referringVolunteer: "Sofi",
  },
  {
    id: "pur-005",
    createdAt: "2026-11-12T09:30:00.000Z",
    buyerName: "Sofía Castiglione",
    buyerEmail: "scastiglione@gmail.com",
    buyerDni: "43888999",
    quantity: 3,
    totalAmount: 36000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812345",
    buyerParticipation: "asistir",
    referringVolunteer: "Nico",
  },
  {
    id: "pur-006",
    createdAt: "2026-11-12T13:40:00.000Z",
    buyerName: "Federico Morales",
    buyerEmail: "fede.morales@hotmail.com",
    buyerDni: "37444111",
    quantity: 2,
    totalAmount: 24000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812346",
    buyerParticipation: "asistir",
    referringVolunteer: "Mili",
  },
  {
    id: "pur-007",
    createdAt: "2026-11-13T11:20:00.000Z",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    buyerDni: "41999222",
    quantity: 5,
    totalAmount: 60000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812347",
    buyerParticipation: "asistir",
    referringVolunteer: "Campi",
  },
  {
    id: "pur-008",
    createdAt: "2026-11-14T15:10:00.000Z",
    buyerName: "Martín Echeverría",
    buyerEmail: "mecheverria@outlook.com",
    buyerDni: "36555444",
    quantity: 2,
    totalAmount: 24000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812348",
    buyerParticipation: "asistir",
    referringVolunteer: "Directa",
  },
  {
    id: "pur-009",
    createdAt: "2026-11-15T08:50:00.000Z",
    buyerName: "Valentina Soler",
    buyerEmail: "vsoler@austral.edu.ar",
    buyerDni: "44123987",
    quantity: 2,
    totalAmount: 24000,
    tierName: "Preventa 1",
    status: "pending",
    mpPaymentId: null,
    buyerParticipation: "asistir",
    referringVolunteer: "Sofi",
  },
  {
    id: "pur-010",
    createdAt: "2026-11-15T19:05:00.000Z",
    buyerName: "Tomás Albarracín",
    buyerEmail: "talbarracin@gmail.com",
    buyerDni: "42345678",
    quantity: 1,
    totalAmount: 12000,
    tierName: "Preventa 1",
    status: "paid",
    mpPaymentId: "mp-pay-90812350",
    buyerParticipation: "donacion",
    referringVolunteer: "Nico",
  },
];

export const MOCK_DASHBOARD_TICKETS: DashboardTicket[] = [
  // De Compra 1 (María González)
  {
    id: "tkt-001",
    qrCode: "TICKET-7A9B-4C12",
    status: "used",
    holderName: "María González",
    holderDni: "40123456",
    isAdult: true,
    diet: "celiaco",
    checkedInAt: "2026-11-20T21:15:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-001",
    buyerName: "María González",
    buyerEmail: "maria.gonzalez@example.com",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-002",
    qrCode: "TICKET-8B0C-5D23",
    status: "used",
    holderName: "Lucas González",
    holderDni: "55123789",
    isAdult: false,
    diet: "vegetariano",
    checkedInAt: "2026-11-20T21:15:00.000Z",
    alcoholAllowance: 0,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 2,
    tierName: "Preventa 1",
    purchaseId: "pur-001",
    buyerName: "María González",
    buyerEmail: "maria.gonzalez@example.com",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-003",
    qrCode: "TICKET-9C1D-6E34",
    status: "used",
    holderName: "Carlos Pérez",
    holderDni: "38987654",
    isAdult: true,
    diet: "sin_carne_viernes",
    checkedInAt: "2026-11-20T21:18:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 3,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-001",
    buyerName: "María González",
    buyerEmail: "maria.gonzalez@example.com",
    referringVolunteer: "Campi",
  },

  // De Compra 2 (Donación Juan Navarro)
  {
    id: "tkt-004",
    qrCode: "TICKET-DONA-0001",
    status: "active",
    holderName: "Donación Comunitaria (1/2)",
    holderDni: "38291234",
    isAdult: true,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-002",
    buyerName: "Juan Manuel Navarro",
    buyerEmail: "juan.navarro@example.com",
    referringVolunteer: "Mili",
  },
  {
    id: "tkt-005",
    qrCode: "TICKET-DONA-0002",
    status: "active",
    holderName: "Donación Comunitaria (2/2)",
    holderDni: "38291234",
    isAdult: true,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-002",
    buyerName: "Juan Manuel Navarro",
    buyerEmail: "juan.navarro@example.com",
    referringVolunteer: "Mili",
  },

  // De Compra 3 (Agustina Rossi)
  {
    id: "tkt-006",
    qrCode: "TICKET-1A2B-3C4D",
    status: "used",
    holderName: "Agustina Rossi",
    holderDni: "42555666",
    isAdult: true,
    diet: "vegetariano",
    checkedInAt: "2026-11-20T21:40:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 1,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-003",
    buyerName: "Agustina Rossi",
    buyerEmail: "agustina.rossi@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-007",
    qrCode: "TICKET-2B3C-4D5E",
    status: "used",
    holderName: "Santiago Ferrara",
    holderDni: "42111000",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T21:40:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 4,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-003",
    buyerName: "Agustina Rossi",
    buyerEmail: "agustina.rossi@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-008",
    qrCode: "TICKET-3C4D-5E6F",
    status: "active",
    holderName: "Florencia Méndez",
    holderDni: "43777888",
    isAdult: true,
    diet: "celiaco",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-003",
    buyerName: "Agustina Rossi",
    buyerEmail: "agustina.rossi@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-009",
    qrCode: "TICKET-4D5E-6F7G",
    status: "active",
    holderName: "Joaquín Martínez",
    holderDni: "41222333",
    isAdult: true,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-003",
    buyerName: "Agustina Rossi",
    buyerEmail: "agustina.rossi@austral.edu.ar",
    referringVolunteer: "Campi",
  },

  // De Compra 4 (Lucas Benítez)
  {
    id: "tkt-010",
    qrCode: "TICKET-5E6F-7G8H",
    status: "used",
    holderName: "Lucas Benítez",
    holderDni: "39112233",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T22:05:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-004",
    buyerName: "Lucas Benítez",
    buyerEmail: "lbenitez@empresa.com",
    referringVolunteer: "Sofi",
  },

  // De Compra 5 (Sofía Castiglione)
  {
    id: "tkt-011",
    qrCode: "TICKET-6F7G-8H9I",
    status: "used",
    holderName: "Sofía Castiglione",
    holderDni: "43888999",
    isAdult: true,
    diet: "celiaco",
    checkedInAt: "2026-11-20T21:50:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 1,
    nonAlcoholicDrinksServed: 2,
    tierName: "Preventa 1",
    purchaseId: "pur-005",
    buyerName: "Sofía Castiglione",
    buyerEmail: "scastiglione@gmail.com",
    referringVolunteer: "Nico",
  },
  {
    id: "tkt-012",
    qrCode: "TICKET-7G8H-9I0J",
    status: "used",
    holderName: "Camila Varela",
    holderDni: "44000111",
    isAdult: true,
    diet: "vegetariano",
    checkedInAt: "2026-11-20T21:50:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-005",
    buyerName: "Sofía Castiglione",
    buyerEmail: "scastiglione@gmail.com",
    referringVolunteer: "Nico",
  },
  {
    id: "tkt-013",
    qrCode: "TICKET-8H9I-0J1K",
    status: "active",
    holderName: "Mateo Castiglione",
    holderDni: "56222333",
    isAdult: false,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 0,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-005",
    buyerName: "Sofía Castiglione",
    buyerEmail: "scastiglione@gmail.com",
    referringVolunteer: "Nico",
  },

  // De Compra 6 (Federico Morales)
  {
    id: "tkt-014",
    qrCode: "TICKET-9I0J-1K2L",
    status: "used",
    holderName: "Federico Morales",
    holderDni: "37444111",
    isAdult: true,
    diet: "sin_carne_viernes",
    checkedInAt: "2026-11-20T22:10:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 3,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-006",
    buyerName: "Federico Morales",
    buyerEmail: "fede.morales@hotmail.com",
    referringVolunteer: "Mili",
  },
  {
    id: "tkt-015",
    qrCode: "TICKET-0J1K-2L3M",
    status: "used",
    holderName: "Lucía Bianchi",
    holderDni: "38999888",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T22:10:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-006",
    buyerName: "Federico Morales",
    buyerEmail: "fede.morales@hotmail.com",
    referringVolunteer: "Mili",
  },

  // De Compra 7 (Clara Domínguez)
  {
    id: "tkt-016",
    qrCode: "TICKET-1K2L-3M4N",
    status: "used",
    holderName: "Clara Domínguez",
    holderDni: "41999222",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T21:30:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-007",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-017",
    qrCode: "TICKET-2L3M-4N5O",
    status: "used",
    holderName: "Esteban Paz",
    holderDni: "41333444",
    isAdult: true,
    diet: "vegetariano",
    checkedInAt: "2026-11-20T21:30:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 3,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-007",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-018",
    qrCode: "TICKET-3M4N-5O6P",
    status: "used",
    holderName: "Bautista Álvarez",
    holderDni: "42000555",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T21:35:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 4,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-007",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-019",
    qrCode: "TICKET-4N5O-6P7Q",
    status: "active",
    holderName: "Victoria Suárez",
    holderDni: "43111222",
    isAdult: true,
    diet: "sin_carne_viernes",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-007",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    referringVolunteer: "Campi",
  },
  {
    id: "tkt-020",
    qrCode: "TICKET-5O6P-7Q8R",
    status: "active",
    holderName: "Ignacio Gil",
    holderDni: "40888777",
    isAdult: true,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-007",
    buyerName: "Clara Domínguez",
    buyerEmail: "clara.dominguez@austral.edu.ar",
    referringVolunteer: "Campi",
  },

  // De Compra 8 (Martín Echeverría)
  {
    id: "tkt-021",
    qrCode: "TICKET-6P7Q-8R9S",
    status: "used",
    holderName: "Martín Echeverría",
    holderDni: "36555444",
    isAdult: true,
    diet: "regular",
    checkedInAt: "2026-11-20T22:25:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 1,
    nonAlcoholicDrinksServed: 1,
    tierName: "Preventa 1",
    purchaseId: "pur-008",
    buyerName: "Martín Echeverría",
    buyerEmail: "mecheverria@outlook.com",
    referringVolunteer: "Directa",
  },
  {
    id: "tkt-022",
    qrCode: "TICKET-7Q8R-9S0T",
    status: "used",
    holderName: "Paula Quiroga",
    holderDni: "37111000",
    isAdult: true,
    diet: "celiaco",
    checkedInAt: "2026-11-20T22:25:00.000Z",
    alcoholAllowance: 5,
    alcoholicDrinksServed: 2,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-008",
    buyerName: "Martín Echeverría",
    buyerEmail: "mecheverria@outlook.com",
    referringVolunteer: "Directa",
  },

  // De Compra 10 (Tomás Albarracín - Donación)
  {
    id: "tkt-023",
    qrCode: "TICKET-DONA-0003",
    status: "active",
    holderName: "Donación Comunitaria (1/1)",
    holderDni: "42345678",
    isAdult: true,
    diet: "regular",
    checkedInAt: null,
    alcoholAllowance: 5,
    alcoholicDrinksServed: 0,
    nonAlcoholicDrinksServed: 0,
    tierName: "Preventa 1",
    purchaseId: "pur-010",
    buyerName: "Tomás Albarracín",
    buyerEmail: "talbarracin@gmail.com",
    referringVolunteer: "Nico",
  },
];

export function calculateKPIs(
  tickets: DashboardTicket[],
  purchases: DashboardPurchase[],
  totalCapacity: number = 300
): DashboardKPIs {
  const paidPurchases = purchases.filter((p) => p.status === "paid");
  const totalRevenue = paidPurchases.reduce((acc, p) => acc + p.totalAmount, 0);
  const totalTicketsSold = tickets.length;
  const totalTicketsCheckedIn = tickets.filter((t) => t.status === "used").length;
  const attendanceRate =
    totalTicketsSold > 0 ? Math.round((totalTicketsCheckedIn / totalTicketsSold) * 100) : 0;
  const capacityRate =
    totalCapacity > 0 ? Math.round((totalTicketsSold / totalCapacity) * 100) : 0;

  let drinksAlcoholicServed = 0;
  let drinksNonAlcoholicServed = 0;

  const dietCounts = {
    regular: 0,
    celiaco: 0,
    vegetariano: 0,
    sin_carne_viernes: 0,
    total: tickets.length,
  };

  for (const ticket of tickets) {
    drinksAlcoholicServed += ticket.alcoholicDrinksServed;
    drinksNonAlcoholicServed += ticket.nonAlcoholicDrinksServed;

    if (ticket.diet in dietCounts) {
      dietCounts[ticket.diet as keyof typeof dietCounts]++;
    } else {
      dietCounts.regular++;
    }
  }

  // Ranking de voluntarios
  const volunteerMap = new Map<
    string,
    { salesCount: number; ticketsCount: number; totalAmount: number }
  >();

  for (const p of paidPurchases) {
    const vol = p.referringVolunteer?.trim() || "Venta Directa";
    const current = volunteerMap.get(vol) || {
      salesCount: 0,
      ticketsCount: 0,
      totalAmount: 0,
    };
    current.salesCount += 1;
    current.ticketsCount += p.quantity;
    current.totalAmount += p.totalAmount;
    volunteerMap.set(vol, current);
  }

  const volunteerRankings = Array.from(volunteerMap.entries())
    .map(([name, stats]) => ({
      name,
      ...stats,
    }))
    .sort((a, b) => b.totalAmount - a.totalAmount);

  return {
    totalRevenue,
    totalTicketsSold,
    totalTicketsCheckedIn,
    attendanceRate,
    totalCapacity,
    capacityRate,
    drinksAlcoholicServed,
    drinksNonAlcoholicServed,
    totalPurchases: paidPurchases.length,
    dietCounts,
    volunteerRankings,
  };
}

export function getMockDashboardData(): DashboardData {
  const kpis = calculateKPIs(MOCK_DASHBOARD_TICKETS, MOCK_DASHBOARD_PURCHASES, 300);

  return {
    eventName: "Peña Folklórica Austral 2026",
    eventDate: "2026-11-20T23:00:00.000Z",
    eventVenue: "Mariano Acosta 1610, B1629 Pilar, Provincia de Buenos Aires",
    tickets: MOCK_DASHBOARD_TICKETS,
    purchases: MOCK_DASHBOARD_PURCHASES,
    kpis,
    isMockData: true,
  };
}
